### PR TITLE
Non-scrollable `ResizablePane`

### LINKED ISSUE #413: MacosTextField expand with ResizablePane crashes
**Description**

A MacosTextField wrapped with Resizable Pane with expand, no maxlines crashes with the error '''FlutterError (The Scrollbar's ScrollController has no ScrollPosition attached.
A Scrollbar cannot be painted without a ScrollPosition.
The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.)'''

Use textfield with generic code like this:
```dart
ResizablePane(
  minSize: 50,
  startSize: 60,
  resizableSide: ResizableSide.top,
  maxSize: MediaQuery.of(context).size.height / 2.5,
  builder: (_, __) {
    return MacosTextField(
      prefix: MacosIcon(CupertinoIcons.money_dollar),
      placeholder: 'Type some text here',
      expands: true,
      maxLines: null,
      showCursor: true,
      clearButtonMode: OverlayVisibilityMode.always,
    );
  },
),
```

### PR DESCRIPTION
**Pull request by stMerlHin**
This PR add new constructor `RezizablePane.noScrollBar` to  `ResizablePane` class.
It allow user to disable the internal `MacosScrollbar` witch is in by default in the `ResizablePaneWidget`

close #413
## Pre-launch Checklist

- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [x] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

### CODE REVIEW

**Comment by stMerlHin** [comment]
Hi @GroovinChip can you review this PR ? Thanks.

File: example/lib/pages/buttons_page.dart [hunk 1]
```diff
@@ -59,16 +59,14 @@ class _ButtonsPageState extends State<ButtonsPage> {
...
-            );
-          },
+        ResizablePane.noScrollBar(
+            minSize: 180,
+            startSize: 200,
+            windowBreakpoint: 700,
+            resizableSide: ResizableSide.right,
+            child: const Center(
+                child: Text('Resizable Pane')
+            )
```
Comment (GroovinChip) [inline example/lib/pages/buttons_page.dart]:
```suggestion
            ),
```
Make sure to run `dart format` after this change is made.

File: lib/src/layout/resizable_pane.dart [hunk 2]
```diff
@@ -30,10 +30,12 @@ enum ResizableSide {
 /// The [startSize] is the initial width or height depending on the orientation of the pane.
 /// {@endtemplate}
 class ResizablePane extends StatefulWidget {
+
+  ///Create a [ResizablePane] with an internal [MacosScrollbar]
```
Comment (GroovinChip) [inline lib/src/layout/resizable_pane.dart]:
```suggestion
  /// Creates a [ResizablePane] with an internal [MacosScrollbar].
```

File: lib/src/layout/resizable_pane.dart [hunk 3]
```diff
@@ -48,14 +50,46 @@ class ResizablePane extends StatefulWidget {
         assert(
           (startSize >= minSize) && (startSize <= maxSize),
           'startSize must not be less than minSize or more than maxWidth',
-        );
+        ) {
+    useScrollBar = true;
+  }
+
+  /// Create a [ResizablePane] without an internal [MacosScrollbar]
+  /// {@macro resizablePane}
```
Comment (GroovinChip) [inline lib/src/layout/resizable_pane.dart]:
```suggestion
  /// Creates a [ResizablePane] without an internal [MacosScrollbar].
  /// {@macro resizablePane}.
```
In between these 2 lines, please add some documentation that describes why this constructor may be useful. It may not be intuitive for some, so docs are preferred.

File: lib/src/layout/resizable_pane.dart [hunk 4]
```diff
@@ -48,14 +50,46 @@ class ResizablePane extends StatefulWidget {
...
   /// The builder that creates a child to display in this widget, which will
   /// use the provided [_scrollController] to enable the scrollbar to work.
   ///
   /// Pass the [scrollController] obtained from this method, to a scrollable
   /// widget used in this method to work with the internal [MacosScrollbar].
-  final ScrollableWidgetBuilder builder;
+  late final ScrollableWidgetBuilder? builder;
+
+  /// The child to display in this widget.
+  /// this is only used when the constructor used is [ResizablePane.noScrollbar]
```
Comment (GroovinChip) [inline lib/src/layout/resizable_pane.dart]:
```suggestion
  /// The child to display in this widget.
  /// 
  /// This is only referenced when the constructor used is [ResizablePane.noScrollbar].
```

File: lib/src/layout/resizable_pane.dart [hunk 5]
```diff
@@ -48,14 +50,46 @@ class ResizablePane extends StatefulWidget {
...
+  late final Widget? child;
```
Comment (GroovinChip) [inline lib/src/layout/resizable_pane.dart]: Why mark this as `late` if it is nullable?

File: lib/src/layout/resizable_pane.dart [hunk 6]
```diff
@@ -48,14 +50,46 @@ class ResizablePane extends StatefulWidget {
...
+
+  /// Specify if this [ResizablePane] should have an internal [MacosScrollbar]
```
Comment (GroovinChip) [inline lib/src/layout/resizable_pane.dart]:
```suggestion
  /// Specify if this [ResizablePane] should have an internal [MacosScrollbar].
```

File: lib/src/layout/resizable_pane.dart [hunk 7]
```diff
@@ -48,14 +50,46 @@ class ResizablePane extends StatefulWidget {
...
+  late final bool useScrollBar;
```
Comment (GroovinChip) [inline lib/src/layout/resizable_pane.dart]: Does this need to be marked late since it gets set in both constructor bodies?

File: CHANGELOG.md [hunk 8]
```diff
@@ -1,3 +1,7 @@
+##[2.0.0-beta.2]
+* Provide `ReziablePane.noScrollBar` constructor which in opposite to the default `ResizablePane` constructor does not have a built in `MaosScrollbar`
+  * The default `ResizablePane`  constructor is not `const` constructor anymore
```
Comment (GroovinChip) [inline CHANGELOG.md]:
```suggestion
🚨 Breaking Changes 🚨
* `ResizablePane` can now disallow the usage of its internal scrollbar via the  `ReziablePane.noScrollBar` constructor. Consequently, this means that the default constructor is no longer `const`.
```

**Review by GroovinChip — CHANGES_REQUESTED** [review]
Thanks for taking this on, @stMerlHin! 

Please merge in the latest changes from `dev` and make the requested changes. Make sure to bump the beta version in the `pubspec` and changelog. Thanks!

**Comment by GroovinChip** [comment]
@stMerlHin this is one of the last issues in play before a stable 2.0 can be released. Do you mind wrapping this up, please?

**Comment by GroovinChip** [comment]
I'm taking this off the 2.0 milestone.

**Comment by stMerlHin** [comment]
Hey @GroovinChip, hope you're fine. I'm really sorry that I didn't give any sign of life. I was a little busy. I will update this PR ASAP.

File: example/lib/pages/buttons_page.dart (hunk 1 above)
Comment (stMerlHin) [reply example/lib/pages/buttons_page.dart]: Ok.

**Comment by stMerlHin** [comment]
image

I actually don't know how to resolve this. It's from dart code metrics check.

**Comment by GroovinChip** [comment]
> image
> 
> I actually don't know how to resolve this. It's from dart code metrics check.

don't worry about this, I'll deal with it

**Comment by GroovinChip** [comment]
> Hey @GroovinChip, hope you're fine. I'm really sorry that I didn't give any sign of life. I was a little busy. I will update this PR ASAP.

No worries mate, I know how it is :)

File: example/lib/pages/buttons_page.dart [hunk 9]
```diff
@@ -61,6 +61,13 @@ class _ButtonsPageState extends State<ButtonsPage> {
         ],
       ),
       children: [
+        const ResizablePane.noScrollBar(
+          minSize: 180,
+          startSize: 200,
+          windowBreakpoint: 700,
+          resizableSide: ResizableSide.right,
+          child: Center(child: Text('Resizable Pane')),
+        ),
```
Comment (GroovinChip) [inline example/lib/pages/buttons_page.dart]: Can we actually put this in the new `ResizablePanePage` please?

File: lib/src/layout/resizable_pane.dart [hunk 10]
```diff
@@ -30,18 +30,54 @@ enum ResizableSide {
 /// The [startSize] is the initial width or height depending on the orientation of the pane.
 /// {@endtemplate}
 class ResizablePane extends StatefulWidget {
-  /// {@macro resizablePane}
+  /// Creates a [ResizablePane] with an internal [MacosScrollbar].
+  ///
+  /// Consider going with [ResizablePane.noScrollBar] constructor if the internal
+  /// [MacosScrollbar] is useless or when dealing with widgets which do not
+  /// expose their scroll controllers.
```
Comment (GroovinChip) [inline lib/src/layout/resizable_pane.dart]:
```suggestion
  /// Consider using [ResizablePane.noScrollBar] constructor when the internal
  /// [MacosScrollbar] is not needed or when working with widgets which do not
  /// expose their scroll controllers.
```

File: lib/src/layout/resizable_pane.dart [hunk 11]
```diff
@@ -30,18 +30,54 @@ enum ResizableSide {
...
+          'startSize must not be less than minSize or more than maxWidth',
+        );
+
+  /// Create a [ResizablePane] without an internal [MacosScrollbar].
+  ///
+  /// Very useful when dealing with widgets which do not expose their scroll
+  /// controllers or when not using the platform scroll bar is preferred.
+  ///
+  /// Consider going with the default constructor if showing [MacosScrollbar]
+  /// when scrolling the content of this widget is the expected behaviour.
```
Comment (GroovinChip) [inline lib/src/layout/resizable_pane.dart]:
```suggestion
  /// Creates a [ResizablePane] without an internal [MacosScrollbar].
  ///
  /// Useful when working with widgets which do not expose their scroll
  /// controllers or when not using the platform scroll bar is preferred.
  ///
  /// Consider using the default constructor if showing a [MacosScrollbar]
  /// when scrolling the content of this widget is the expected behavior.
```

**Review by GroovinChip — CHANGES_REQUESTED** [review]

**Comment by GroovinChip** [comment]
@stMerlHin the DCM action is failing because your PR is from a fork, we can just ignore this check.

File: example/lib/pages/buttons_page.dart (hunk 9 above)
Comment (GroovinChip) [reply example/lib/pages/buttons_page.dart]: Just update one of the existing panes on that screen to be non-scrollable

Comment (stMerlHin) [reply example/lib/pages/buttons_page.dart]: Yeah, sure !

Comment (stMerlHin) [reply example/lib/pages/buttons_page.dart]: sure.

**Review by GroovinChip — APPROVED** [review]
@stMerlHin Looks good but I think you need to run pub get, I don't see updated lock files

**Comment by stMerlHin** [comment]
> @stMerlHin Looks good but I think you need to run pub get, I don't see updated lock files

Will do so.

**Review by GroovinChip — APPROVED** [review]
LGTM!
