### PR TITLE
Version 1.0.1

### LINKED ISSUE #218: `MacosColorWell` should account for non-macOS platforms
Currently, `MacosColorWell` does not account for the possibility that it will be used on platforms other than macOS. As such, when clicked, it should either:
* Throw an  `UnsupportedPlatformException`
* Open a non-platform dependent color picker'

I am undecided about which option is better. I welcome anyone's thoughts on the matter.

### LINKED ISSUE #221: Styling improvements for the graphical `MacosTimePicker`
- [ ] Improve the border gradient
- [ ] Improve the inner shadow

### PR DESCRIPTION
**Pull request by GroovinChip**
### Changes
* Improvements to the graphical `MacosTimePicker`
  * Better color gradient on the border
  * Better inner shadow
  * Minor size adjustments
  * API improvements
* Throw an exception if `MacosColorWell` is clicked on a non-macOS platform

Screen Shot 2022-05-05 at 10 38 30 AM

Closes #221 and #218

## Pre-launch Checklist

- [x] I have run `dartfmt` on all changed files 
- [x] I have incremented the package version as appropriate and updated `CHANGELOG.md` with my changes 
- [x] I have added/updated relevant documentation 
- [x] I have run "optimize/organize imports" on all changed files
- [x] I have addressed all analyzer warnings as best I could

### CODE REVIEW

File: test/selectors/date_picker_test.dart [hunk 1]
```diff
@@ -5,7 +5,8 @@ import 'package:macos_ui/macos_ui.dart';
 
 void main() {
   group('MacosDatePicker tests', () {
-    testWidgets('MacosDatePicker renders the expected date', (tester) async {
+    testWidgets('textual MacosDatePicker renders the expected date',
```
Comment (whiplashoo) [inline test/selectors/date_picker_test.dart]:
```suggestion
    testWidgets('Textual MacosDatePicker renders the expected date',
```

**Review by whiplashoo — COMMENTED** [review]
LGTM
